#:schema node_modules/wrangler/config-schema.json
name = "sublink1-worker"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "052a76f2039f40b28d609ab41e35267a" }
]

[assets]
directory = "./public"
